######################################################################
# Automatically generated by qmake (2.01a) Tue Jul 31 19:00:55 2012
######################################################################

TEMPLATE = app
TARGET =
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += \
	rwindow.h \
	perlinnoise.h \
    fakecpp11.h

SOURCES += \
	main.cpp \
	rwindow.cpp \
	perlinnoise.cpp
